# Generated by Django 4.1.3 on 2022-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("company", "email")},
        ),
    ]
