# Generated by Django 4.1.3 on 2022-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_company_name_alter_employee_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="thumbnail",
            field=models.ImageField(default=1, editable=False, upload_to="thumbs"),
            preserve_default=False,
        ),
    ]
